version: "3.3"
services:



  postgres-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: twitcher-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    image: twitcher-api:0.0.1
    ports:
      - "3000:3000"
    depends_on:
      - postgres-db
    environment:
      - NODE_ENV={NODE_ENV}

volumes:
  postgres-data:
