version: "3.3"
name: twitcher-network
networks:
    twitcher-network:
      name: twitcher-network
      driver: bridge

services:
  postgres-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: twitcher-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - twitcher-network

  twitcher-api:
    #image: twitcher-api:0.0.1
    build:
      context: .
      dockerfile: ./apps/twitcher-api/Dockerfile
      target: development
    command: yarn run start:dev twitcher-api
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres-db
    environment:
      - NODE_ENV={NODE_ENV}
    networks:
      - twitcher-network

volumes:
  postgres-data:
