name: ENV VARIABLES
on:
  push:
    branches:
      - main
      - dev
# if Declared here it means that it is a global variable available for all jobs
env:
  APP_PORT: 3000
  DB_PORT: 5432
  DB_USER: admin
  DB_PASS: admin
  DB_NAME: twitcher_db

jobs:
  test:
    # env: # if Declared here it means that it is a local variable available for this job only
    #   PORT: 3000
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/yarn.lock.json') }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      # - name: Run server
      #   run: npm start & npx wait-on http://127.0.0.1:$APP_PORT
      - name: Run tests
        run: yarn test
      - name: Output information
        run: echo "POSGRES NAME:${{ env.DB_NAME }}"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "DEPLOYING"
