name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Heyooo
        run: echo "Hello World from Github Actions"
      - name: Print Bye
        run: echo "Byeeeee!"

    
  
